basePath: /
definitions:
  proxy.RequestProxy:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Proxy Server App
  title: Proxy Server
  version: "1.0"
paths:
  /proxy:
    get:
      consumes:
      - application/json
      description: get all history
      produces:
      - application/json
      responses:
        "502":
          description: Internal server error
          schema:
            type: string
      summary: get all requests and responses
      tags:
      - proxy
    post:
      consumes:
      - application/json
      description: create request
      parameters:
      - description: request data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/proxy.RequestProxy'
      produces:
      - application/json
      responses:
        "400":
          description: Invalid request body
          schema:
            type: string
        "502":
          description: Internal server error
          schema:
            type: string
      summary: request url
      tags:
      - proxy
  /proxy/{id}:
    get:
      consumes:
      - application/json
      description: get all history
      parameters:
      - description: request id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Invalid request body
          schema:
            type: string
        "502":
          description: Internal server error
          schema:
            type: string
      summary: get all requests and responses
      tags:
      - proxy
swagger: "2.0"
